# Generated by Django 5.1.6 on 2025-02-24 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='User_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
